export const ROOM_HOTSPOTS = [
  // Room 0: About
  { room: 0, xMin: 220, xMax: 450, id: 'desk', message: ["Ah, the central workstation.", "Many nights were spent here parsing raw server logs.", "Press F to view my full Resume."], link: "https://drive.google.com/file/d/1Y4hG6jPrAm2S5b5AyEGamBIKRndbd23N/view?usp=sharing" },
  { room: 0, xMin: 10, xMax: 120, id: 'books', message: ["A shelf of coding grimoires.", "'React for Masterminds', 'The C++ Standard', 'Bash Secrets'."], link: null },
  { room: 0, xMin: 400, xMax: 500, id: 'portrait', message: ["A pixel portrait of Vansh.", "Looking incredibly sharp today as usual."], link: null },

  // Room 1: Skills — shelves at x=40(w82), x=225(w82), x=410(w82), x=595(w82)
  // Hotspot centers: 81, 266, 451, 636  — each needs ±60px trigger radius
  { room: 1, xMin: 20,  xMax: 143, id: 'frontend', message: ["FRONTEND SHELF.", "React, Next.js, TypeScript — pixel-perfect UIs.", "This is where components are born."], link: null },
  { room: 1, xMin: 205, xMax: 328, id: 'backend',  message: ["BACKEND SHELF.", "Node.js, Python, PostgreSQL, REST & GraphQL.", "The engine room of the stack."], link: null },
  { room: 1, xMin: 390, xMax: 513, id: 'tools',    message: ["TOOLS SHELF.", "Git, Docker, AWS, CI/CD — the ops arsenal.", "The server cat guards this shelf. Meow.", "It watches over Docker deployments all night."], link: null },
  { room: 1, xMin: 560, xMax: 720, id: 'airust',   message: ["AI & RUST SHELF.", "TensorFlow, PyTorch, LLMs — ML stack.", "Rust & WASM for systems-level power.", "Where logic meets machine learning."], link: null },

  // Room 2: Projects (x goes up to 1600 internally inside Room 2)
  { room: 2, xMin: 60, xMax: 180, id: 'proj1', message: ["AskMyNotes is a premium AI-powered study platform built at a hackathon.", "It lets students upload PDFs and interact with their material via AI analysis.", "Features include PDF parsing, citation-backed chat, and a voice tutor.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/Askmynotes-Mavericks", liveLink: "https://askmynotesmavericks.vercel.app/" },
  { room: 2, xMin: 245, xMax: 365, id: 'proj2', message: ["VolunteerConnect is a full-stack JWT-authenticated volunteer platform.", "Built with Node.js + Express REST API and JWT-based authentication.", "Features event workflows, dashboards, and organization management.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/VolunteerConnect", liveLink: "https://volunteer-connect-frontend-orpin.vercel.app/" },
  { room: 2, xMin: 430, xMax: 550, id: 'proj3', message: ["WEAVE is a decentralized real-time collaborative whiteboard built on WebRTC.", "Uses Yjs CRDTs for automatic conflict resolution across concurrent edits.", "AI-powered sticky note summarization helps condense brainstorming clusters.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/WEAVE", liveLink: "https://weave-frontend.onrender.com/" },
  { room: 2, xMin: 615, xMax: 735, id: 'proj4', message: ["NexusPark is a production-deployed smart parking management system.", "Applies Strategy, State, Factory, and Observer patterns to real-world problems.", "Features real-time slot tracking and dynamic hourly pricing.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/Smart-Parking-Management-System", liveLink: "https://smart-parking-management-system-topaz.vercel.app/" },
  { room: 2, xMin: 800, xMax: 920, id: 'proj5', message: ["Beyond Limits is a full-stack CMS blog platform with a cinematic design.", "Uses Supabase Auth with native PostgreSQL Row-Level Security (RLS).", "Gemini Pro generates editorial summaries once when a post is published.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/Beyond-Limits", liveLink: "https://beyond-limits-omega.vercel.app/" },
  { room: 2, xMin: 985, xMax: 1105, id: 'proj6', message: ["AmalGus is India's first digital marketplace for architectural glass.", "Centerpiece is a two-layer AI Smart Matcher interpreting plain-language queries.", "Supports four distinct user roles with personalized hero sections.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/amalgus-new", liveLink: "https://amalgus-new.vercel.app/" },
  { room: 2, xMin: 1170, xMax: 1290, id: 'proj7', message: ["Mentora is a mentorship and learning platform built with React 18 and Firebase.", "Features XP-based leaderboards, session booking, and progress dashboards.", "Built with Firebase (Auth + Firestore) and Framer Motion transitions.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/Mentora", liveLink: "https://mentora-beta.vercel.app/" },
  { room: 2, xMin: 1355, xMax: 1475, id: 'proj8', message: ["Quickstack is a fullstack benchmark tool for Redis caching strategies.", "Visualizes read-through, cache-aside, and cache warming in real-time.", "Built entirely in TypeScript with Next.js 13+ and Redis.", "Press F for Source, L for Live Demo."], link: "https://github.com/Vansh0204/Quickstack-Next.js-Redis-", liveLink: "https://quickstack-rho.vercel.app/" },
  { room: 2, xMin: 1510, xMax: 1600, id: 'trophy', message: ["The Golden Committer Trophy.", "Awarded for surviving the 2026 deployment crisis."], link: null },

  // Room 3: Open Source
  { room: 3, xMin: 10, xMax: 160, id: 'pr1', message: ["Contributed a bug fix to Turborepo — Vercel's production build system.", "Resolved issue #11192 in the build pipeline via PR #11146.", "Turborepo is used by thousands of engineering teams worldwide.", "Click F to see the PR."], link: "https://github.com/vercel/turborepo/pull/11146" },
  { room: 3, xMin: 220, xMax: 360, id: 'pr2', message: ["Contributed 4 pull requests to p5.js — a global creative coding library.", "Resolved issue #7712 across multiple distinct scenarios and edge cases.", "Used by over 10 million students and artists globally.", "Click F to see the PR."], link: "https://github.com/processing/p5.js/pull/8294" },
  { room: 3, xMin: 420, xMax: 560, id: 'pr3', message: ["Contributed a fix to Fastify — one of the fastest Node.js web frameworks.", "Resolved issue #6284 via PR #6608 in a large-scale production codebase.", "Fastify processes 76,000+ requests per second.", "Click F to see the PR."], link: "https://github.com/fastify/fastify/pull/6608" },
  { room: 3, xMin: 620, xMax: 760, id: 'pr4', message: ["Contributed a fix to expressjs/cors — middleware for 50M+ weekly downloads.", "Resolved issue #333 via PR #400 addressing cross-origin edge cases.", "Used in virtually every Express.js application on the internet.", "Click F to see the PR."], link: "https://github.com/expressjs/cors/pull/400" },

  // Room 4: Contact
  { room: 4, xMin: 200, xMax: 340, id: 'mailbox', message: ["The Mailbox.", "You reach inside and find Vansh's contact card:", "Email: vansh65ag@gmail.com", "Mobile: +91 9411068533", "Press F to send an email."], link: "mailto:vansh65ag@gmail.com" },
  { room: 4, xMin: 580, xMax: 720, id: 'house', message: ["The Pixel Cabin.", "Locked from the outside. Authorized developers only."], link: null },
  { room: 4, xMin: 660, xMax: 800, id: 'sign', message: ["NOTICE BOARD.", "'Looking for a robust engineer to architect complex systems?'", "'Look no further!'"], link: "https://twitter.com/vansh" }
];
